[package]
name = "cryptobasics"
version = "0.1.0"
authors = ["Ahmed Fasih <wuzzyview@gmail.com>"]
build = "build.rs"

[dependencies]
openssl = "0.10.9"
rustc-serialize = "0.3"

[build-dependencies]
gcc = "0.3"
